################################################################
# YAML config file to set up vars

database:
  name: swapDB
  host: localhost
  port: 27017
  max_batch_size: 1e5
  metadata:
    - mag
    - mag_err
csv_types:
  classification_id: int
  user_id: int
  annotation: int
  gold_label: int
  object_id: int
  subject_id: int

  machine_score: float
  mag: float
  mag_err: float