################################################################
# YAML config file to set up vars

database:
  name: swapDB
  host: localhost
  port: 27017
  metadata:
    magnitude: mag
    magnitude_error: mag_err